version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    ports:
      - "8001:80"
      - "${VITE_PORT:-5173}:${VITE_PORT:-5173}"
    environment:
      WWWUSER: "${WWWUSER:-1000}"
      WWWGROUP: "${WWWGROUP:-1000}"
      LARAVEL_SAIL: 1
      XDEBUG_MODE: "${SAIL_XDEBUG_MODE:-off}"
      XDEBUG_CONFIG: "${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}"
      IGNITION_LOCAL_SITES_PATH: "${PWD}"
    volumes:
      - .:/var/www/html
    command: >
      sh -c "
        until [ -f composer.json ]; do echo 'Aștept codul să fie montat...'; sleep 2; done &&
        composer install &&
        npm install &&
        npm run build &&
        php artisan migrate --seed &&
        php artisan serve --host=0.0.0.0 --port=80
      "
      
  mysql:
    image: mysql/mysql-server:8.0
    container_name: mysql
    ports:
      - "${FORWARD_DB_PORT:-3306}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD:-root}"
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: "${DB_DATABASE:-laravel}"
      MYSQL_USER: "${DB_USERNAME:-laravel}"
      MYSQL_PASSWORD: "${DB_PASSWORD:-root}"
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - sail-mysql:/var/lib/mysql
    networks:
      - sail

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "${FORWARD_REDIS_PORT:-6379}:6379"
    volumes:
      - sail-redis:/data
    networks:
      - sail

  meilisearch:
    image: getmeili/meilisearch:latest
    container_name: meilisearch
    ports:
      - "${FORWARD_MEILISEARCH_PORT:-7700}:7700"
    environment:
      MEILI_NO_ANALYTICS: "${MEILISEARCH_NO_ANALYTICS:-false}"
    volumes:
      - sail-meilisearch:/meili_data
    networks:
      - sail

  mailpit:
    image: axllent/mailpit:latest
    container_name: mailpit
    ports:
      - "${FORWARD_MAILPIT_PORT:-1025}:1025"
      - "${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025"
    networks:
      - sail

  selenium:
    image: selenium/standalone-chromium
    container_name: selenium
    volumes:
      - /dev/shm:/dev/shm
    networks:
      - sail

volumes:
  sail-mysql:
  sail-redis:
  sail-meilisearch:

networks:
  sail:
    driver: bridge
