version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.local
    container_name: totalaspres-app-local
    restart: unless-stopped
    ports:
      - "8001:80"
    environment:
      APP_ENV: local
      APP_DEBUG: true
      APP_URL: http://localhost:8001
      DB_CONNECTION: sqlite
      DB_DATABASE: /var/www/html/database/database.sqlite
      REDIS_HOST: redis
      REDIS_PASSWORD: null
      REDIS_PORT: 6379
    volumes:
      - .:/var/www/html:cached
      - /var/www/html/node_modules
      - /var/www/html/vendor
    depends_on:
      - redis
    networks:
      - totalaspres-local
    working_dir: /var/www/html

  redis:
    image: redis:7-alpine
    container_name: totalaspres-redis-local
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data-local:/data
    networks:
      - totalaspres-local

volumes:
  redis-data-local:
    driver: local

networks:
  totalaspres-local:
    driver: bridge
