services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: totalaspres-app
    restart: unless-stopped
    ports:
      - "8001:80"
    environment:
      APP_ENV: production
      APP_DEBUG: false
      DB_CONNECTION: sqlite
      DB_DATABASE: /var/www/html/database/database.sqlite
    depends_on:
      - redis
    networks:
      - totalaspres

  redis:
    image: redis:7-alpine
    container_name: totalaspres-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - totalaspres

volumes:
  redis-data:
    driver: local

networks:
  totalaspres:
    driver: bridge
