version: '3.8'

services:
  app:
    build: .
    ports:
      - "8001:80"
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
    restart: unless-stopped
    
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - redis-data:/data

volumes:
  redis-data:
