version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    restart: unless-stopped
    ports:
      - "8001:80"
    environment:
      WWWUSER: "${WWWUSER:-1000}"
      WWWGROUP: "${WWWGROUP:-1000}"
      DB_CONNECTION: sqlite
      DB_DATABASE: /var/www/html/database/database.sqlite
    volumes:
      - .:/var/www/html:cached
      - /var/www/html/node_modules
      - /var/www/html/vendor
    depends_on:
      - redis
    networks:
      - sail
    command: >
      sh -c "
        echo 'Starting Laravel application...' &&
        if [ ! -f /var/www/html/composer.json ]; then
          echo 'Error: Code not mounted properly. Check volume configuration.';
          exit 1;
        fi &&
        echo 'Installing PHP dependencies...' &&
        composer install --no-dev --optimize-autoloader &&
        echo 'Installing Node.js dependencies...' &&
        npm ci &&
        echo 'Building assets...' &&
        npm run build &&
        echo 'Setting up database...' &&
        touch /var/www/html/database/database.sqlite &&
        php artisan migrate --force &&
        echo 'Clearing caches...' &&
        php artisan config:clear &&
        php artisan cache:clear &&
        php artisan route:clear &&
        php artisan view:clear &&
        echo 'Starting web server...' &&
        php artisan serve --host=0.0.0.0 --port=80
      "      
  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "${FORWARD_REDIS_PORT:-6379}:6379"
    volumes:
      - sail-redis:/data
    networks:
      - sail

volumes:
  sail-redis:
    driver: local

networks:
  sail:
    driver: bridge
